version: '3'

services:

  kpu_shop:
     image: kpujaehak/myshop:last
     hostname: '{{.Node.Hostname}}'
     networks:
       - kpu_overlay_network
     ports:
       - 5050:5001
     deploy:
       replicas: 2
       placement:
         constraints:
          - node.role == worker
   
  another_shop:
     image: kpujaehak/product_web
     hostname: '{{.Node.Hostname}}'
     networks:
       - kpu_overlay_network
     ports:
       - 5051:80
     deploy:
       replicas: 2
       placement:
         constraints:
          - node.role == worker
networks:
  kpu_overlay_network:
