version: '3'

services:

  kpu_shop:
     image: kpujaehak/myshop:last
     hostname: '{{.Node.Hostname}}'
     ports:
       - 5050:5001
     deploy:
       replicas: 3
       placement:
         constraints:
          - node.role == worker
   
  another_shop:
     image: kpujaehak/product_web
     hostname: '{{.Node.Hostname}}'
     ports:
       - 5051:80
     deploy:
       replicas: 3
       placement:
         constraints:
          - node.role == worker
